//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOUONG
    {
        public int IDDOUONG { get; set; }
        public int IDDM { get; set; }
        public string TENDOUONG { get; set; }
        public double DONGIA { get; set; }
    
        public virtual DANHMUC_DOUONG DANHMUC_DOUONG { get; set; }
    }
}
