//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public int IDHOADON { get; set; }
        public int IDBAN { get; set; }
        public string TenMon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual TableFood TableFood { get; set; }
    }
}
