//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLCaPheEntities12 : DbContext
    {
        public QLCaPheEntities12()
            : base("name=QLCaPheEntities12")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DANHMUC_DOUONG> DANHMUC_DOUONG { get; set; }
        public virtual DbSet<DOUONG> DOUONGs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<TableFood> TableFoods { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<HOADON_OLD> HOADON_OLD { get; set; }
    
        public virtual int DELETE_DANHMUC(Nullable<int> iDDM)
        {
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_DANHMUC", iDDMParameter);
        }
    
        public virtual int DELETE_DOUONG(Nullable<int> iDDOUONG)
        {
            var iDDOUONGParameter = iDDOUONG.HasValue ?
                new ObjectParameter("IDDOUONG", iDDOUONG) :
                new ObjectParameter("IDDOUONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_DOUONG", iDDOUONGParameter);
        }
    
        public virtual ObjectResult<GetTableList_Result> GetTableList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTableList_Result>("GetTableList");
        }
    
        public virtual int INSERT_DANHMUC(string tENDM)
        {
            var tENDMParameter = tENDM != null ?
                new ObjectParameter("TENDM", tENDM) :
                new ObjectParameter("TENDM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DANHMUC", tENDMParameter);
        }
    
        public virtual int INSERT_DOUONG(Nullable<int> iDDM, string tENDOUONG, Nullable<double> dONGIA)
        {
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            var tENDOUONGParameter = tENDOUONG != null ?
                new ObjectParameter("TENDOUONG", tENDOUONG) :
                new ObjectParameter("TENDOUONG", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_DOUONG", iDDMParameter, tENDOUONGParameter, dONGIAParameter);
        }
    
        public virtual int INSERT_HOA_DON(Nullable<int> iDBAN, string tenMon, Nullable<int> soLuong, Nullable<int> donGia, Nullable<int> thanhTien)
        {
            var iDBANParameter = iDBAN.HasValue ?
                new ObjectParameter("IDBAN", iDBAN) :
                new ObjectParameter("IDBAN", typeof(int));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_HOA_DON", iDBANParameter, tenMonParameter, soLuongParameter, donGiaParameter, thanhTienParameter);
        }
    
        public virtual int InsertTableList(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTableList", aParameter);
        }
    
        public virtual ObjectResult<LOAD_DANHMUC_Result> LOAD_DANHMUC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DANHMUC_Result>("LOAD_DANHMUC");
        }
    
        public virtual ObjectResult<LOAD_DOUONG_Result> LOAD_DOUONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DOUONG_Result>("LOAD_DOUONG");
        }
    
        public virtual ObjectResult<LOAD_DOUONG_ID_Result> LOAD_DOUONG_ID(Nullable<int> iDDM)
        {
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DOUONG_ID_Result>("LOAD_DOUONG_ID", iDDMParameter);
        }
    
        public virtual ObjectResult<LOAD_DOUONG_WITH_WHERE_Result> LOAD_DOUONG_WITH_WHERE(Nullable<int> mADM)
        {
            var mADMParameter = mADM.HasValue ?
                new ObjectParameter("MADM", mADM) :
                new ObjectParameter("MADM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_DOUONG_WITH_WHERE_Result>("LOAD_DOUONG_WITH_WHERE", mADMParameter);
        }
    
        public virtual ObjectResult<LOAD_HOA_DON_Result> LOAD_HOA_DON()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_HOA_DON_Result>("LOAD_HOA_DON");
        }
    
        public virtual ObjectResult<LOAD_INDSDOUONG_Result> LOAD_INDSDOUONG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_INDSDOUONG_Result>("LOAD_INDSDOUONG");
        }
    
        public virtual int ThemTableList(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemTableList", aParameter);
        }
    
        public virtual ObjectResult<TIM_TENDOUONG_Result> TIM_TENDOUONG(string tEN)
        {
            var tENParameter = tEN != null ?
                new ObjectParameter("TEN", tEN) :
                new ObjectParameter("TEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TIM_TENDOUONG_Result>("TIM_TENDOUONG", tENParameter);
        }
    
        public virtual int UPDATE_DANHMUC(Nullable<int> iDDM, string tENDM)
        {
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            var tENDMParameter = tENDM != null ?
                new ObjectParameter("TENDM", tENDM) :
                new ObjectParameter("TENDM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DANHMUC", iDDMParameter, tENDMParameter);
        }
    
        public virtual int UPDATE_DOUONG(Nullable<int> iDDOUONG, Nullable<int> iDDM, string tENDOUONG, Nullable<double> dONGIA)
        {
            var iDDOUONGParameter = iDDOUONG.HasValue ?
                new ObjectParameter("IDDOUONG", iDDOUONG) :
                new ObjectParameter("IDDOUONG", typeof(int));
    
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            var tENDOUONGParameter = tENDOUONG != null ?
                new ObjectParameter("TENDOUONG", tENDOUONG) :
                new ObjectParameter("TENDOUONG", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DOUONG", iDDOUONGParameter, iDDMParameter, tENDOUONGParameter, dONGIAParameter);
        }
    
        public virtual int INSERT_NHANVIEN(string tENNV, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH)
        {
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_NHANVIEN", tENNVParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter);
        }
    
        public virtual int INSERT_TAIKHOAN(string tENTK, string mATKHAU, string qUYEN, Nullable<int> iDNV)
        {
            var tENTKParameter = tENTK != null ?
                new ObjectParameter("TENTK", tENTK) :
                new ObjectParameter("TENTK", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var qUYENParameter = qUYEN != null ?
                new ObjectParameter("QUYEN", qUYEN) :
                new ObjectParameter("QUYEN", typeof(string));
    
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_TAIKHOAN", tENTKParameter, mATKHAUParameter, qUYENParameter, iDNVParameter);
        }
    
        public virtual ObjectResult<LOAD_NHANVIEN_Result> LOAD_NHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_NHANVIEN_Result>("LOAD_NHANVIEN");
        }
    
        public virtual int INSERT_HOADON_OLD(Nullable<int> iDBAN, string tENNV, string tENMONAN, Nullable<System.DateTime> nGAYLAP, Nullable<double> tONGTIEN)
        {
            var iDBANParameter = iDBAN.HasValue ?
                new ObjectParameter("IDBAN", iDBAN) :
                new ObjectParameter("IDBAN", typeof(int));
    
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var tENMONANParameter = tENMONAN != null ?
                new ObjectParameter("TENMONAN", tENMONAN) :
                new ObjectParameter("TENMONAN", typeof(string));
    
            var nGAYLAPParameter = nGAYLAP.HasValue ?
                new ObjectParameter("NGAYLAP", nGAYLAP) :
                new ObjectParameter("NGAYLAP", typeof(System.DateTime));
    
            var tONGTIENParameter = tONGTIEN.HasValue ?
                new ObjectParameter("TONGTIEN", tONGTIEN) :
                new ObjectParameter("TONGTIEN", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_HOADON_OLD", iDBANParameter, tENNVParameter, tENMONANParameter, nGAYLAPParameter, tONGTIENParameter);
        }
    
        public virtual int ThanhToanTableList(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThanhToanTableList", aParameter);
        }
    
        public virtual ObjectResult<LOAD_TAIKHOAN_Result> LOAD_TAIKHOAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_TAIKHOAN_Result>("LOAD_TAIKHOAN");
        }
    
        public virtual ObjectResult<LOADTAIKHOAN_Result> LOADTAIKHOAN(string tK, string mK)
        {
            var tKParameter = tK != null ?
                new ObjectParameter("TK", tK) :
                new ObjectParameter("TK", typeof(string));
    
            var mKParameter = mK != null ?
                new ObjectParameter("MK", mK) :
                new ObjectParameter("MK", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADTAIKHOAN_Result>("LOADTAIKHOAN", tKParameter, mKParameter);
        }
    
        public virtual ObjectResult<LOADTAIKHOANVANHANVIEN_Result> LOADTAIKHOANVANHANVIEN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADTAIKHOANVANHANVIEN_Result>("LOADTAIKHOANVANHANVIEN");
        }
    
        public virtual ObjectResult<LOADTAIKHOANVANHANVIEN2_Result> LOADTAIKHOANVANHANVIEN2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADTAIKHOANVANHANVIEN2_Result>("LOADTAIKHOANVANHANVIEN2");
        }
    
        public virtual ObjectResult<LOADTAIKHOANVANHANVIEN3_Result> LOADTAIKHOANVANHANVIEN3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADTAIKHOANVANHANVIEN3_Result>("LOADTAIKHOANVANHANVIEN3");
        }
    
        public virtual ObjectResult<LOADHOADON_OLD_Result> LOADHOADON_OLD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADHOADON_OLD_Result>("LOADHOADON_OLD");
        }
    
        public virtual int DELETE_HOA_DON(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON", idbanParameter);
        }
    
        public virtual int DeleteBanDaThanhToan(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteBanDaThanhToan", idbanParameter);
        }
    
        public virtual int EDIT_HOA_DON(Nullable<int> iDBAN, string tenMon, Nullable<int> soLuong, Nullable<int> donGia, Nullable<int> thanhTien)
        {
            var iDBANParameter = iDBAN.HasValue ?
                new ObjectParameter("IDBAN", iDBAN) :
                new ObjectParameter("IDBAN", typeof(int));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDIT_HOA_DON", iDBANParameter, tenMonParameter, soLuongParameter, donGiaParameter, thanhTienParameter);
        }
    
        public virtual int DELETE_HOA_DON2(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("idban", idban) :
                new ObjectParameter("idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON2", idbanParameter);
        }
    
        public virtual ObjectResult<LOAD_HOA_DON_NEW_Result> LOAD_HOA_DON_NEW()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_HOA_DON_NEW_Result>("LOAD_HOA_DON_NEW");
        }
    
        public virtual int DELETE_HOA_DON3(Nullable<int> idHD)
        {
            var idHDParameter = idHD.HasValue ?
                new ObjectParameter("idHD", idHD) :
                new ObjectParameter("idHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON3", idHDParameter);
        }
    
        public virtual int EDIT_HOA_DON_NEW(Nullable<int> iDHD, string tenMon, Nullable<int> soLuong, Nullable<int> donGia, Nullable<int> thanhTien)
        {
            var iDHDParameter = iDHD.HasValue ?
                new ObjectParameter("IDHD", iDHD) :
                new ObjectParameter("IDHD", typeof(int));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDIT_HOA_DON_NEW", iDHDParameter, tenMonParameter, soLuongParameter, donGiaParameter, thanhTienParameter);
        }
    
        public virtual int DELETE_DOUONG2(Nullable<int> iDDOUONG)
        {
            var iDDOUONGParameter = iDDOUONG.HasValue ?
                new ObjectParameter("IDDOUONG", iDDOUONG) :
                new ObjectParameter("IDDOUONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_DOUONG2", iDDOUONGParameter);
        }
    
        public virtual int DELETE_DOUONG3(Nullable<int> iDDOUONG)
        {
            var iDDOUONGParameter = iDDOUONG.HasValue ?
                new ObjectParameter("IDDOUONG", iDDOUONG) :
                new ObjectParameter("IDDOUONG", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_DOUONG3", iDDOUONGParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_POSITION(string tENDOUONG, Nullable<double> dONGIA)
        {
            var tENDOUONGParameter = tENDOUONG != null ?
                new ObjectParameter("TENDOUONG", tENDOUONG) :
                new ObjectParameter("TENDOUONG", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_POSITION", tENDOUONGParameter, dONGIAParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_POSITION2(Nullable<int> iDDM, string tENDOUONG, Nullable<double> dONGIA)
        {
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            var tENDOUONGParameter = tENDOUONG != null ?
                new ObjectParameter("TENDOUONG", tENDOUONG) :
                new ObjectParameter("TENDOUONG", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_POSITION2", iDDMParameter, tENDOUONGParameter, dONGIAParameter);
        }
    
        public virtual int UPDATE_DOUONG2(Nullable<int> iDDOUONG, string tENDOUONG, Nullable<double> dONGIA)
        {
            var iDDOUONGParameter = iDDOUONG.HasValue ?
                new ObjectParameter("IDDOUONG", iDDOUONG) :
                new ObjectParameter("IDDOUONG", typeof(int));
    
            var tENDOUONGParameter = tENDOUONG != null ?
                new ObjectParameter("TENDOUONG", tENDOUONG) :
                new ObjectParameter("TENDOUONG", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_DOUONG2", iDDOUONGParameter, tENDOUONGParameter, dONGIAParameter);
        }
    
        public virtual ObjectResult<LOADTAIKHOANVANHANVIEN4_Result> LOADTAIKHOANVANHANVIEN4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADTAIKHOANVANHANVIEN4_Result>("LOADTAIKHOANVANHANVIEN4");
        }
    
        public virtual int DELETE_TAI_KHOAN_VA_NHAN_VIEN(Nullable<int> idHD)
        {
            var idHDParameter = idHD.HasValue ?
                new ObjectParameter("idHD", idHD) :
                new ObjectParameter("idHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_TAI_KHOAN_VA_NHAN_VIEN", idHDParameter);
        }
    
        public virtual int ConfigureCascadeDelete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ConfigureCascadeDelete");
        }
    
        public virtual int DELETE_TAI_KHOAN_VA_NHAN_VIEN2(Nullable<int> idHD)
        {
            var idHDParameter = idHD.HasValue ?
                new ObjectParameter("idHD", idHD) :
                new ObjectParameter("idHD", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_TAI_KHOAN_VA_NHAN_VIEN2", idHDParameter);
        }
    
        public virtual int DELETE_NHAN_VIEN_VA_TK(Nullable<int> iDNV)
        {
            var iDNVParameter = iDNV.HasValue ?
                new ObjectParameter("IDNV", iDNV) :
                new ObjectParameter("IDNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_NHAN_VIEN_VA_TK", iDNVParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_POSITION_NV_TK(string tENNV, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH, string tENTK, string mATKHAU, string qUYEN)
        {
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var tENTKParameter = tENTK != null ?
                new ObjectParameter("TENTK", tENTK) :
                new ObjectParameter("TENTK", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var qUYENParameter = qUYEN != null ?
                new ObjectParameter("QUYEN", qUYEN) :
                new ObjectParameter("QUYEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_POSITION_NV_TK", tENNVParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter, tENTKParameter, mATKHAUParameter, qUYENParameter);
        }
    
        public virtual int UPDATE_NV_TK(Nullable<int> idNV, string tENNV, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH, string tENTK, string mATKHAU, string qUYEN)
        {
            var idNVParameter = idNV.HasValue ?
                new ObjectParameter("idNV", idNV) :
                new ObjectParameter("idNV", typeof(int));
    
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var tENTKParameter = tENTK != null ?
                new ObjectParameter("TENTK", tENTK) :
                new ObjectParameter("TENTK", typeof(string));
    
            var mATKHAUParameter = mATKHAU != null ?
                new ObjectParameter("MATKHAU", mATKHAU) :
                new ObjectParameter("MATKHAU", typeof(string));
    
            var qUYENParameter = qUYEN != null ?
                new ObjectParameter("QUYEN", qUYEN) :
                new ObjectParameter("QUYEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_NV_TK", idNVParameter, tENNVParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter, tENTKParameter, mATKHAUParameter, qUYENParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_DO_UONG(Nullable<int> iDDM, string tENDOUONG, Nullable<double> dONGIA)
        {
            var iDDMParameter = iDDM.HasValue ?
                new ObjectParameter("IDDM", iDDM) :
                new ObjectParameter("IDDM", typeof(int));
    
            var tENDOUONGParameter = tENDOUONG != null ?
                new ObjectParameter("TENDOUONG", tENDOUONG) :
                new ObjectParameter("TENDOUONG", typeof(string));
    
            var dONGIAParameter = dONGIA.HasValue ?
                new ObjectParameter("DONGIA", dONGIA) :
                new ObjectParameter("DONGIA", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_DO_UONG", iDDMParameter, tENDOUONGParameter, dONGIAParameter);
        }
    
        public virtual ObjectResult<LOAD_TK_DE_LOGIN_Result> LOAD_TK_DE_LOGIN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_TK_DE_LOGIN_Result>("LOAD_TK_DE_LOGIN");
        }
    
        public virtual ObjectResult<LOAD_TK_DE_LOGIN2_Result> LOAD_TK_DE_LOGIN2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_TK_DE_LOGIN2_Result>("LOAD_TK_DE_LOGIN2");
        }
    
        public virtual ObjectResult<LOAD_TK_DE_LOGIN3_Result> LOAD_TK_DE_LOGIN3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_TK_DE_LOGIN3_Result>("LOAD_TK_DE_LOGIN3");
        }
    
        public virtual ObjectResult<LOADTAIKHOANVANHANVIEN5_Result> LOADTAIKHOANVANHANVIEN5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOADTAIKHOANVANHANVIEN5_Result>("LOADTAIKHOANVANHANVIEN5");
        }
    
        public virtual ObjectResult<LOAD_TK_NHAN_VIEN_DE_TIM_Result> LOAD_TK_NHAN_VIEN_DE_TIM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_TK_NHAN_VIEN_DE_TIM_Result>("LOAD_TK_NHAN_VIEN_DE_TIM");
        }
    
        public virtual int XOA_BAN(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("Idban", idban) :
                new ObjectParameter("Idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOA_BAN", idbanParameter);
        }
    
        public virtual int XOA_TABLE(Nullable<int> idban)
        {
            var idbanParameter = idban.HasValue ?
                new ObjectParameter("Idban", idban) :
                new ObjectParameter("Idban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOA_TABLE", idbanParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_TABLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_TABLE");
        }
    
        public virtual int DELETE_ALL_HOA_DON(Nullable<int> iDban)
        {
            var iDbanParameter = iDban.HasValue ?
                new ObjectParameter("IDban", iDban) :
                new ObjectParameter("IDban", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_ALL_HOA_DON", iDbanParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_TABLE2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_TABLE2");
        }
    
        public virtual int Them_DATA_VAO_TABLE(Nullable<int> a, string tenkh)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            var tenkhParameter = tenkh != null ?
                new ObjectParameter("Tenkh", tenkh) :
                new ObjectParameter("Tenkh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Them_DATA_VAO_TABLE", aParameter, tenkhParameter);
        }
    
        public virtual ObjectResult<Get_ALL_Table_Result> Get_ALL_Table()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ALL_Table_Result>("Get_ALL_Table");
        }
    
        public virtual int XOA_MON_CUOI_CUNG_TRONG_LIST_VIEW(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOA_MON_CUOI_CUNG_TRONG_LIST_VIEW", aParameter);
        }
    
        public virtual int DELETE_HOA_DON_VOI_ID(Nullable<int> iDhoaDon)
        {
            var iDhoaDonParameter = iDhoaDon.HasValue ?
                new ObjectParameter("IDhoaDon", iDhoaDon) :
                new ObjectParameter("IDhoaDon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_HOA_DON_VOI_ID", iDhoaDonParameter);
        }
    
        public virtual int INSERT_IN_FIRST_AVAILABLE_HOA_DON(Nullable<int> iDBAN, string tenMon, Nullable<int> soLuong, Nullable<int> donGia, Nullable<int> thanhTien)
        {
            var iDBANParameter = iDBAN.HasValue ?
                new ObjectParameter("IDBAN", iDBAN) :
                new ObjectParameter("IDBAN", typeof(int));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_IN_FIRST_AVAILABLE_HOA_DON", iDBANParameter, tenMonParameter, soLuongParameter, donGiaParameter, thanhTienParameter);
        }
    
        public virtual int SP_INSERT_OR_UPDATE_IN_FIRST_AVAILABLE_HOA_DON(Nullable<int> iDBAN, string tenMon, Nullable<int> soLuong, Nullable<int> donGia)
        {
            var iDBANParameter = iDBAN.HasValue ?
                new ObjectParameter("IDBAN", iDBAN) :
                new ObjectParameter("IDBAN", typeof(int));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_OR_UPDATE_IN_FIRST_AVAILABLE_HOA_DON", iDBANParameter, tenMonParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int INSERT_HOADON_THANH_TOAN(Nullable<int> iDBAN, string tENNV, string tENMONAN, string tENKH, Nullable<System.DateTime> nGAYLAP, Nullable<double> tONGTIEN)
        {
            var iDBANParameter = iDBAN.HasValue ?
                new ObjectParameter("IDBAN", iDBAN) :
                new ObjectParameter("IDBAN", typeof(int));
    
            var tENNVParameter = tENNV != null ?
                new ObjectParameter("TENNV", tENNV) :
                new ObjectParameter("TENNV", typeof(string));
    
            var tENMONANParameter = tENMONAN != null ?
                new ObjectParameter("TENMONAN", tENMONAN) :
                new ObjectParameter("TENMONAN", typeof(string));
    
            var tENKHParameter = tENKH != null ?
                new ObjectParameter("TENKH", tENKH) :
                new ObjectParameter("TENKH", typeof(string));
    
            var nGAYLAPParameter = nGAYLAP.HasValue ?
                new ObjectParameter("NGAYLAP", nGAYLAP) :
                new ObjectParameter("NGAYLAP", typeof(System.DateTime));
    
            var tONGTIENParameter = tONGTIEN.HasValue ?
                new ObjectParameter("TONGTIEN", tONGTIEN) :
                new ObjectParameter("TONGTIEN", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_HOADON_THANH_TOAN", iDBANParameter, tENNVParameter, tENMONANParameter, tENKHParameter, nGAYLAPParameter, tONGTIENParameter);
        }
    
        public virtual ObjectResult<LOAD_HOA_DON_THANH_TOAN_Result> LOAD_HOA_DON_THANH_TOAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOAD_HOA_DON_THANH_TOAN_Result>("LOAD_HOA_DON_THANH_TOAN");
        }
    
        public virtual int ThanhToanTableList2(Nullable<int> a)
        {
            var aParameter = a.HasValue ?
                new ObjectParameter("a", a) :
                new ObjectParameter("a", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThanhToanTableList2", aParameter);
        }
    }
}
